// Generated by CoffeeScript 1.10.0
(function() {
  var client, request, should;

  should = require('should');

  request = require('request-json');

  client = request.createClient('http://localhost:3000/');

  describe('Customer', function() {
    var id_customer;
    id_customer = null;
    describe('POST /customer', function() {
      var customer;
      customer = null;
      before(function(done) {
        customer = {
          name: 'roli butron',
          email: 'rolib2@gmail.com',
          preferred_barber: 'test'
        };
        return done();
      });
      return it('should return OK', function(done) {
        return client.post('customer/', customer, function(err, res, body) {
          res.statusCode.should.be.exactly(200);
          id_customer = res.body._id;
          return done();
        });
      });
    });
    describe('POST /customer', function() {
      var customer;
      customer = null;
      before(function(done) {
        customer = {
          name: 'Juan vargas',
          email: 'juangmail.com',
          preferred_barber: 'test test'
        };
        return done();
      });
      return it('should return status code 400 email invalid', function(done) {
        return client.post('customer/', customer, function(err, res, body) {
          res.statusCode.should.be.exactly(400);
          return done();
        });
      });
    });
    return describe('POST /customer', function() {
      var customer;
      customer = null;
      before(function(done) {
        customer = {
          name: 'alex aguilar',
          email: 'rolib2@gmail.com',
          preferred_barber: 'test 2'
        };
        return done();
      });
      return it('should return status 400 Email already exists', function(done) {
        return client.post('customer/', customer, function(err, res, body) {
          res.statusCode.should.be.exactly(400);
          return done();
        });
      });
    });
  });

}).call(this);
