// Generated by CoffeeScript 1.10.0
(function() {
  var customer, mongoose, schema;

  mongoose = require('mongoose');

  schema = mongoose.Schema;

  customer = new schema({
    name: {
      type: String,
      required: true
    },
    email: {
      type: String,
      required: true,
      unique: true
    },
    preferred_barber: {
      type: String,
      required: true
    }
  });

  module.exports = mongoose.model('customer', customer);

}).call(this);
